// Module: dashboard — consolidated Playwright specs (2 test cases).
// Generated by JBS IntelliQE. Tests are numbered sequentially within this file.

import { test, expect } from '@playwright/test';

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("001 - Verify dashboard displays the authenticated user's basic information after login", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page.locator(".oxd-userdropdown-name")).toContainText("", { timeout: 15000 });
  await expect(page.getByRole("heading", { name: "Dashboard" })).toContainText("Dashboard", { timeout: 15000 });
  await expect(page.getByText("Quick Launch")).toBeVisible({ timeout: 15000 });
  await expect(page.getByText("Time at Work")).toBeVisible({ timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("002 - Verify direct navigation to dashboard URL without a session redirects to login", async ({ page }) => {
  await page.goto("/web/index.php/dashboard/index");
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/auth/login"), { timeout: 15000 });
  await expect(page.getByRole("button", { name: "Login" })).toBeVisible({ timeout: 15000 });
  await expect(page.getByPlaceholder("Username")).toBeVisible({ timeout: 15000 });
  await expect(page.locator("nav.oxd-navbar")).toBeHidden({ timeout: 15000 });
  await expect(page.locator(".oxd-topbar-header-breadcrumb")).toBeHidden({ timeout: 15000 });
  await expect(page.locator(".oxd-sidepanel")).toBeHidden({ timeout: 15000 });
});
