// Module: authentication — consolidated Playwright specs (9 test cases).
// Generated by JBS IntelliQE. Tests are numbered sequentially within this file.

import { test, expect } from '@playwright/test';

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("001 - Verify successful login with valid credentials redirects to dashboard", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/dashboard/index"), { timeout: 15000 });
  await expect(page.getByRole("heading", { name: "Dashboard" })).toBeVisible({ timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("002 - Verify 'Required' message appears below Username when submitted empty", async ({ page }) => {
  await page.goto("/login");
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Required", { exact: true })).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Required", { exact: true })).toContainText("Required", { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("003 - Verify 'Required' message appears below Password when submitted empty", async ({ page }) => {
  await page.goto("/");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Required", { exact: true })).toContainText("", { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("https://opensource-demo\\.orangehrmlive\\.com/web/index\\.php/auth/login"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("004 - Verify 'Required' message appears under both fields when both submitted empty", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Required", { exact: true }).nth(0)).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Required", { exact: true }).nth(1)).toContainText("Required", { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("005 - Verify login fails with 'Invalid credentials' for wrong password", async ({ page }) => {
  await page.goto("/login");
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("wrongPass999");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Invalid credentials")).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toBeVisible({ timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/auth/login"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("006 - Verify login fails with 'Invalid credentials' for unknown username (no enumeration)", async ({ page }) => {
  await page.goto("/login");
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("nonexistentUser42");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Invalid credentials")).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toBeVisible({ timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toContainText("Invalid credentials", { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("007 - Verify whitespace-only entries do not pass validation as non-empty", async ({ page }) => {
  await page.goto("/");
  await page.getByPlaceholder("Username").fill("   ");
  await page.getByPlaceholder("Password").fill("   ");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Required", { exact: true }).nth(0)).toBeVisible({ timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("https://opensource-demo\\.orangehrmlive\\.com/web/index\\.php/auth/login"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("008 - Verify password field masks input and is not exposed in the URL", async ({ page }) => {
  await page.goto("/login");
  await page.goto("/web/index.php/auth/login");
  await expect(page).toHaveURL(new RegExp("https://"), { timeout: 15000 });
  await page.getByPlaceholder("Password").fill("admin123");
  await expect(page.locator("input[name=\"password\"][type=\"password\"]")).toBeVisible({ timeout: 15000 });
  await page.getByPlaceholder("Username").fill("");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page).toHaveURL(new RegExp("dashboard"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("009 - Verify 'Forgot your password?' link navigates to the password recovery page", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByText("Forgot your password?")).toBeVisible({ timeout: 15000 });
  await page.getByText("Forgot your password?").click();
  await expect(page).toHaveURL(new RegExp("/auth/requestPasswordResetCode"), { timeout: 15000 });
  await expect(page.getByPlaceholder("Username")).toBeVisible({ timeout: 15000 });
  await expect(page.getByRole("button", { name: "Reset Password" })).toBeVisible({ timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/auth/requestPasswordResetCode"), { timeout: 15000 });
});
